#!/bin/bash
###########

ADDRESS=http://localhost/tracker-panel/endpoint.php?torrent-add

while read line; do
	FILE="$line"
	NAME=$(basename "$FILE" | sed 's/.torrent//g')
	HASH=$(./torrentinfo -H $FILE)
	SIZE=$(./torrentinfo -v -k info.length $FILE)

	echo "adding hash with name: $NAME, size: $SIZE and hash: $HASH\n"
	curl --data "{ \"hash\":\"$HASH\", \"name\": \"$NAME\", \"size\":\"$SIZE\"}" $ADDRESS
done
